# https://github.com/RustSec/cargo-audit/blob/master/audit.toml.example

[advisories]
ignore = ["RUSTSEC-2020-0031"]

# Output Configuration
[output]
deny = ["warnings"] # exit on error if warnings are found
